### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by oukohou** [lucidrains/bottleneck-transformer-pytorch#1]
Great work! Are the pretrained models availabel?

**Comment by amiltonwong** [comment]
I don't think so. It's mentioned that TPU x 3 were used in the original paper. Just wait for the official release of the pretrained model :P

**Comment by BIGBALLON** [comment]
> Great work! Are the pretrained models availabel?

A pytorch version: https://github.com/BIGBALLON/distribuuuu/blob/master/distribuuuu/models/botnet.py, 

The results (the model trained by [distribuuuu](https://github.com/BIGBALLON/distribuuuu)) :

|                    model                     | epoch |    total batch     | lr policy | base lr | Acc@1  | Acc@5  |                                                           model / config                                                           |
| :------------------------------------------: | :---: | :----------------: | :-------: | :-----: | :----: | :----: | :--------------------------------------------------------------------------------------------------------------------------------: |
|                   resnet18                   |  100  |   256 (32*8GPUs)   |    cos    |   0.2   | 70.902 | 89.894 | [Google Drive](https://drive.google.com/file/d/18a6QFc_DoTHo3TWkN_EsptyGmhF97sVw/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/resnet18.yaml) |
|                   resnet18                   |  100  |  1024 (128*8GPUs)  |    cos    |   0.8   | 70.994 | 89.892 |                                                                                                                                    |
|                   resnet18                   |  100  | 8192 (128*64GPUs)  |    cos    |   6.4   | 70.165 | 89.374 |                                                                                                                                    |
|                   resnet18                   |  100  | 16384 (256*64GPUs) |    cos    |  12.8   | 68.766 | 88.381 |                                                                                                                                    |
|                   resnet50                   |  100  |   256 (32*8GPUs)   |    cos    |   0.2   | 77.252 | 93.430 | [Google Drive](https://drive.google.com/file/d/1rUY1mSYTxe7jWzzcWrreg398tbSNXtnv/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/resnet50.yaml) |
| [botnet50](https://arxiv.org/abs/2101.11605) |  100  |   256 (32*8GPUs)   |    cos    |   0.2   | 77.604 | 93.682 | [Google Drive](https://drive.google.com/file/d/1-jvhJaMyy-KziAuFnmt5rkoZrm5364UF/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/botnet50.yaml) |


Training log: https://gist.github.com/BIGBALLON/3d53c81b2b11ea5dd66417c2a985cd89

@oukohou

**Comment by oukohou** [comment]
@BIGBALLON yeah thanks for your work! I will try that later.Great thanks again.

**Comment by biki18** [comment]
Hello, I am having some problems with your pre-trained model. I would like to ask how should I use botnet50.pth. I found no **state_dict** in it to load when I tried to run it. Then I tried to unzip it and only found a **data.pkl** file. And when I tried to load it, I got an error: _pickle.UnpicklingError: A load persistent id instruction was encountered.

**Comment by biki18** [comment]
> > Great work! Are the pretrained models availabel?
> 
> A pytorch version: https://github.com/BIGBALLON/distribuuuu/blob/master/distribuuuu/models/botnet.py,
> 
> The results (the model trained by [distribuuuu](https://github.com/BIGBALLON/distribuuuu)) :
> 
> model	epoch	total batch	lr policy	base lr	Acc@1	Acc@5	model / config
> resnet18	100	256 (32*8GPUs)	cos	0.2	70.902	89.894	[Google Drive](https://drive.google.com/file/d/18a6QFc_DoTHo3TWkN_EsptyGmhF97sVw/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/resnet18.yaml)
> resnet18	100	1024 (128*8GPUs)	cos	0.8	70.994	89.892	
> resnet18	100	8192 (128*64GPUs)	cos	6.4	70.165	89.374	
> resnet18	100	16384 (256*64GPUs)	cos	12.8	68.766	88.381	
> resnet50	100	256 (32*8GPUs)	cos	0.2	77.252	93.430	[Google Drive](https://drive.google.com/file/d/1rUY1mSYTxe7jWzzcWrreg398tbSNXtnv/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/resnet50.yaml)
> [botnet50](https://arxiv.org/abs/2101.11605)	100	256 (32*8GPUs)	cos	0.2	77.604	93.682	[Google Drive](https://drive.google.com/file/d/1-jvhJaMyy-KziAuFnmt5rkoZrm5364UF/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/botnet50.yaml)
> Training log: https://gist.github.com/BIGBALLON/3d53c81b2b11ea5dd66417c2a985cd89
> 
> @oukohou

Hi, You really did a great job. But I am having some problems with your pre-trained model. I would like to ask how should I use botnet50.pth. I found no **state_dict** in it to load when I tried to run it. Then I tried to unzip it and only found a **data.pkl** file. And when I tried to load it, I got an error: _pickle.UnpicklingError: A load persistent id instruction was encountered.
@BIGBALLON

**Comment by xiaoWen9246** [comment]
@BIGBALLON   when I open the botnet50' model Hyperlink, Google Drive indicates that the file doesn't exist.

**Comment by luobo555** [comment]
> 

me too

**Comment by rookiiiie** [comment]
> > Great work! Are the pretrained models availabel?
> 
> A pytorch version: https://github.com/BIGBALLON/distribuuuu/blob/master/distribuuuu/models/botnet.py,
> 
> The results (the model trained by [distribuuuu](https://github.com/BIGBALLON/distribuuuu)) :
> 
> model	epoch	total batch	lr policy	base lr	Acc@1	Acc@5	model / config
> resnet18	100	256 (32*8GPUs)	cos	0.2	70.902	89.894	[Google Drive](https://drive.google.com/file/d/18a6QFc_DoTHo3TWkN_EsptyGmhF97sVw/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/resnet18.yaml)
> resnet18	100	1024 (128*8GPUs)	cos	0.8	70.994	89.892	
> resnet18	100	8192 (128*64GPUs)	cos	6.4	70.165	89.374	
> resnet18	100	16384 (256*64GPUs)	cos	12.8	68.766	88.381	
> resnet50	100	256 (32*8GPUs)	cos	0.2	77.252	93.430	[Google Drive](https://drive.google.com/file/d/1rUY1mSYTxe7jWzzcWrreg398tbSNXtnv/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/resnet50.yaml)
> [botnet50](https://arxiv.org/abs/2101.11605)	100	256 (32*8GPUs)	cos	0.2	77.604	93.682	[Google Drive](https://drive.google.com/file/d/1-jvhJaMyy-KziAuFnmt5rkoZrm5364UF/view?usp=sharing) / [cfg](https://github.com/BIGBALLON/distribuuuu/blob/master/config/botnet50.yaml)
> Training log: https://gist.github.com/BIGBALLON/3d53c81b2b11ea5dd66417c2a985cd89
> 
> @oukohou

hello！ the botnet50 pre-trained model's Hyperlink doesn't work,can you share it for me,thank you！

**Comment by oukohou** [comment]
@rookiiiie leave an email and i will send it to you.

**Comment by rookiiiie** [comment]
my email is：gusiyuan155@126.com

**Comment by rookiiiie** [comment]
> @rookiiiie leave an email and i will send it to you.

my email is：gusiyuan155@126.com

**Comment by hefei12** [comment]
> @rookiiiie leave an email and i will send it to you.

hello！ the botnet50 pre-trained model's Hyperlink doesn't work,can you share it for me,thank you！
my email is : 15935498018@163.com

**Comment by artemgalyan** [comment]
> @rookiiiie leave an email and i will send it to you.

Hello! Can you please send pre-trained botnet50 model to me? My email is gaa.ww87@gmail.com
Thank you!

**Comment by oukohou** [comment]
![image](https://github.com/lucidrains/bottleneck-transformer-pytorch/assets/16237619/2758c1c9-8c22-4d83-b85e-fa124f2aa2d2)
sent. Don't know if this behavior is appropriate, maybe you all contact the author first.

**Comment by Dindy-R** [comment]
> 留下电子邮件，我会把它发送给你。

Hello, the botent50.pth 

> @rookiiiie leave an email and i will send it to you.
hello, can y sent pretrained botnet50 to me? my email: Dindy-R@outlook.com

**Comment by Dindy-R** [comment]
> @rookiiiie leave an email and i will send it to you.

hello, can y sent pretrained botnet50 to me? my email : Dindy-R@outlook.com

**Comment by xinzhichao** [comment]
hello, can y sent pretrained botnet50 to me? my email : xinzhichaomail@foxmail.com

**Comment by oukohou** [comment]
closing as my problem is solved, people who wants weights may contact the author first.
