### ISSUE TITLE
Feature map size

### ISSUE THREAD

**Issue by benlee73** [lucidrains/bottleneck-transformer-pytorch#10]
hi
In my case, the input images size are all different, so the feature map size keeps changing.
In this case, how should the fmap_size parameter of BottleStack be set?
Is it possible to learn with an unfixed feature map size?

**Comment by lucidrains** [comment]
unfortunately not with the way relative positional encoding is done atm

**Comment by lucidrains** [comment]
there is a way to do this with another type of relative positional encoding, but it would require deviating from the paper

**Comment by benlee73** [comment]
thank you for the reply.
We will preprocess the input image size through padding.
