### ISSUE TITLE
Do you have complete code(such as mask rcnn+BoTNet),I have v100  GPU,I can try to train the model and share it

### ISSUE THREAD

**Issue by JackWhite-rwx** [lucidrains/bottleneck-transformer-pytorch#2]
Do you have complete code(such as mask rcnn+BoTNet),I have v100  GPU,I can try to train the model and share it with your github

**Comment by lucidrains** [comment]
@JackWhite-rwx you'll have to do the model surgery yourself, but here's an example for BotNet! https://github.com/lucidrains/bottleneck-transformer-pytorch#botnet

**Comment by JackWhite-rwx** [comment]
> @JackWhite-rwx you'll have to do the model surgery yourself, but here's an example for BotNet! https://github.com/lucidrains/bottleneck-transformer-pytorch#botnet

Thank you very much ,I will try to do it.
