### ISSUE TITLE
A little bug.

### ISSUE THREAD

**Issue by lartpang** [lucidrains/bottleneck-transformer-pytorch#3]
https://github.com/lucidrains/bottleneck-transformer-pytorch/blob/b789de6db39f33854862fbc9bcee27c697cf003c/bottleneck_transformer_pytorch/bottleneck_transformer_pytorch.py#L16

It is necessary to specify the equipment here.

```python
flat_pad = torch.zeros((b, h, l - 1), device = device, dtype = dtype) 
```

**Comment by lucidrains** [comment]
fixed in the latest, thanks!
