### ISSUE TITLE
How should I modify the code if the input feature map has unequal width and height?

### ISSUE THREAD

**Issue by ShuweiShao** [lucidrains/bottleneck-transformer-pytorch#4]
Assume that the width and height of the feature map are 10 and 8, respectively.
Could you please help me to check that the modification about the class RelPosEmb is correct?

class RelPosEmb(nn.Module):
    def __init__(
        self,
        fmap_size,
        dim_head
    ):
        super().__init__()
        scale = dim_head ** -0.5
        self.fmap_size = fmap_size
        self.scale = scale
        # self.rel_height = nn.Parameter(torch.randn(fmap_size * 2 - 1, dim_head) * scale)
        self.rel_height = nn.Parameter(torch.randn(8 * 2 - 1, dim_head) * scale)
        # self.rel_width = nn.Parameter(torch.randn(fmap_size * 2 - 1, dim_head) * scale)
        self.rel_width = nn.Parameter(torch.randn(10* 2 - 1, dim_head) * scale)

    def forward(self, q):
        q = rearrange(q, 'b h (x y) d -> b h x y d', x = 8)
        rel_logits_w = relative_logits_1d(q, self.rel_width)
        rel_logits_w = rearrange(rel_logits_w, 'b h x i y j-> b h (x y) (i j)')

        q = rearrange(q, 'b h x y d -> b h y x d')
        rel_logits_h = relative_logits_1d(q, self.rel_height)
        rel_logits_h = rearrange(rel_logits_h, 'b h x i y j -> b h (y x) (j i)')
        return rel_logits_w + rel_logits_h

**Comment by lucidrains** [comment]
@kekege-sw yup, that should be correct!

**Comment by lucidrains** [comment]
@kekege-sw the first bottle block also goes through a downsample, so you'll have to account for the fact that the fmap size may be 5 and 4 in later blocks

**Comment by lucidrains** [comment]
@kekege-sw I've updated the code so you can enter the height and the width of the feature map as a tuple

```python
import torch
from torch import nn
from torchvision.models import resnet50

from bottleneck_transformer_pytorch import BottleStack

layer = BottleStack(
    dim = 256,
    fmap_size = (56, 54),
    dim_out = 1024,
    proj_factor = 4,
    downsample = True,
    heads = 4,
    dim_head = 128,
    rel_pos_emb = True,
    activation = nn.ReLU()
)

resnet = resnet50()

# model surgery

backbone = list(resnet.children())

model = nn.Sequential(
    *backbone[:5],
    layer,
    nn.AdaptiveAvgPool2d((1, 1)),
    nn.Flatten(1),
    nn.Linear(1024, 1000)
)

# use the 'BotNet'

img = torch.randn(2, 3, 224, 216)
preds = model(img) # (2, 1000)

```

**Comment by ShuweiShao** [comment]
OK! Thanks for prompt reply.
