### ISSUE TITLE
Tensorflow / Keras implementation ? 

### ISSUE THREAD

**Issue by Cyril9227** [lucidrains/bottleneck-transformer-pytorch#7]
Thanks for the amazing work. I was wondering if a TF version was in the work ? 

Cheers

**Comment by lucidrains** [comment]
Thanks for the kind words

The original paper already had a TF implementation , which I largely based the code in this repo off of https://gist.github.com/aravindsrinivas/56359b79f0ce4449bcb04ab4b56a57a2

**Comment by Cyril9227** [comment]
Thanks !
